### ISSUE TITLE
fix: s3.Bucket.fromBucketName scope argument type

### ISSUE THREAD

**Issue by k33rs** [aws-samples/data-lake-as-code#16]
Code version:
* branch: mainline
* commit: [57766358d414da5f427f0786fffe85dce48c2244](https://github.com/aws-samples/data-lake-as-code/commit/57766358d414da5f427f0786fffe85dce48c2244)
* bug location: [bin/aws.ts line 23](https://github.com/aws-samples/data-lake-as-code/blob/57766358d414da5f427f0786fffe85dce48c2244/bin/aws.ts#L23)

Steps to reproduce:
* `git clone` the project
* `npm install`
* uncomment [bin/aws.ts lines 22-26](https://github.com/aws-samples/data-lake-as-code/blob/57766358d414da5f427f0786fffe85dce48c2244/bin/aws.ts#L22)
* `cdk synth CoreDataLake ExampleS3DataSet`

Expected output:
```
App at '' should be created in the scope of a Stack, but no Stack found
Subprocess exited with error 1
```

As of AWS CDK 1.70.0, [s3.Bucket.fromBucketName](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#static-from-wbr-bucket-wbr-namescope-id-bucketname) expects the type of its first argument (`scope`) to be `Construct`, not `App`.

Proposed solution:

Initialise the S3 bucket in [lib/ExampleS3DataSet-stack.ts line 26](https://github.com/aws-samples/data-lake-as-code/blob/57766358d414da5f427f0786fffe85dce48c2244/lib/ExampleS3DataSet-stack.ts#L26) instead of passing it as a prop:
```javascript
sourceBucket: s3.Bucket.fromBucketName(this, 'exampleS3DataSetSourceBucket', '--- YOUR EXISTING BUCKET NAME GOES HERE ---'),
```

**Comment by paulu-aws** [comment]
@k33rs thanks for pointing that out! 

I've added a simple `exisitingResourceImportStack` in the `aws.ts` file as essentially an empty stack that can be passed as scope to the various CDK import/from..() methods for resources created **outside** of the CDK app itself. We were sort of reusing the coreDataLake stack for this purpose before. For example:

```
const exampleExistingIamUser = iam.User.fromUserName(coreDataLake, 'exampleUserGrantee', '--- EXISTING IAM USERNAME GOES HERE --' );
```
I always felt like a bit of a hack because the resource being imported had no real relationship to the coreDataLake stack. So using the `exisitingResourceImportStack` should look like this:
```
const exampleExistingIamUser = iam.User.fromUserName(exisitingResourceImportStack, 'exampleUserGrantee', '--- EXISTING IAM USERNAME GOES HERE --' );
```
I don't think this actually has any impact on the synthed templates but hopefully reads a bit cleaner.
